### ISSUE TITLE
Delete/close seen movies

### ISSUE THREAD

**Issue by ghost** [TimeoutZero/browse-by-netflixters#16]
Guys, if we could add a feature to close the all movies that we already saw it would be great! How many times we spend a lot of time trying to figure out movies in a catalog full of seen stuff :D ... so in a story format:

As a Netflix Viewer
I would like to be able to Hide/Unhide movies that I already seen
So I can speed up the process of choosing something new to watch.

**Comment by carloshpds** [comment]
Sorry for late reply @rafaelcavazin, my life was a mess!
... It looks like another extension to me! :)

I'll add this to my projects list and let you know about any news ;)
